version: "3.8"

services:
  # 1. Dịch vụ Database MySQL
  db_mysql:
    image: mysql:8.0
    container_name: law_mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: legalbot_password
      MYSQL_DATABASE: law_chatbot_db
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql # Lưu dữ liệu ra thư mục mysql_data để không bị mất khi tắt Docker
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - law_network

  # 2. Dịch vụ Vector Database Qdrant
  qdrant:
    image: qdrant/qdrant:latest
    container_name: law_qdrant_container
    restart: always
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_data:/qdrant/storage # Lưu dữ liệu vector ra thư mục qdrant_data
    networks:
      - law_network

networks:
  law_network:
    driver: bridge
